Meals QR Scan & API functionallity.
hackupc/myhackupc pull request #169
Opened 2022-02-01 20:13 UTC by EncryptEx

## Patch Notes
Created / Made the HTML page to scan QR codes at any meal of the event. 
JavaScript's background added.
POST requests done.
Fixed issues with CSRF's tokens and session IDs

## Additional Notes (optional)

Would need to fix and error of duplication of instances of ``babel-polyfill`` Caused by bootstrap and instascan (library used)

## Some questions
- [ x ] I have read the contributing guidelines
- [ x ] I abide by this repository Code of Conduct
- [ x ] I understand that my PR won't be merged until GitHub gives a "green light"

2022-02-03 19:16 UTC, Casassarnau requested changes

2022-02-03 19:16 UTC, Casassarnau commented on meals/templates/meal_checkin.html
Si borres la linia de sota torna la navbar

2022-02-03 19:16 UTC, Casassarnau commented on meals/templates/meal_checkin.html
> +            <a class="btn btn-default btn-block" href="{% url 'meals_list' %}">< Back</a>
Aixo a poder ser estar dins de la div de sota i  sota de tot per a que es vegi a sota el video, seria molt top

2022-02-09 18:12 UTC, EncryptEx commented on meals/templates/meal_checkin.html
(https://github.com/hackupc/myhackupc/blob/474739e2a21210344c23ac6f6c6fce4f436fe719/meals/templates/meal_checkin.html#L16)

2022-02-11 15:59 UTC, Casassarnau approved these changes
Nice

2022-02-11 16:00 UTC, merged